### ISSUE TITLE
Ubuntu-18.04上跑不了这个正则

### ISSUE THREAD

**Issue by ipcjs** [PinkD/rime-pinyin-zhwiki#1]
这个正则在Ubuntu-18.04 for Windows 10上完全跑不了：
https://github.com/PinkD/rime-pinyin-zhwiki/blob/master/Makefile#L25

改成这样才没报错：
```
grep -P '^[\x{4e00}-\x{9fa5}]{2,8}$$' $(FILENAME) > zhwiki_pinyin.raw
```

你用的是什么版本的grep，居然支持`\uffff`？

参考：
http://www.regular-expressions.info/unicode.html

**Comment by PinkD** [comment]
ArchLinux ， `grep (GNU grep) 3.4`
`grep -V` 看看什么版本？

**Comment by ipcjs** [comment]
`grep (GNU grep) 3.1`

ArchLinux的版本号果然更新的快（

**Comment by ipcjs** [comment]
看来是我搞错版本了，系统应该是Ubuntu 18.04 (-_-#)

**Comment by cainmagi** [comment]
同样的问题也出现在了Ubuntu 24.04.2 LTS上

我这里`grep -V`的结果是`grep (GNU grep) 3.11`

直接使用当前版本（[76b8606](https://github.com/PinkD/rime-pinyin-zhwiki/commit/76b8606a8e12522b063c69deae69c261a727243e)）的结果是

```txt
grep -P $'^[\u4e00-\u9fa5]{2,8}$' zhwiki-latest-all-titles-in-ns0 > zhwiki_pinyin.raw
grep: PCRE2 does not support \F, \L, \l, \N{name}, \U, or \u
make: *** [Makefile:25: zhwiki_pinyin.raw] Error 2
```

按照楼主的方法修改以后`make`才能正常运行。

奇怪的是，单独在bash里运行以下命令
```sh
grep -P $'^[\u4e00-\u9fa5]{2,8}$' zhwiki-latest-all-titles-in-ns0 > zhwiki_pinyin.raw
```
是没问题的。

但是同样的命令在makefile里
```makefile
zhwiki_pinyin.raw: $(FILENAME)
	grep -P $$'^[\u4e00-\u9fa5]{2,8}$$' $(FILENAME) > zhwiki_pinyin.raw
```
就会有上面那样的报错。
